In [1]:
import requests
import sqlite3
import pandas as pd

In [2]:
#data extraction for people
url = 'https://swapi.dev/api/people/'
all_people = []

while url:
    response = requests.get(url)
    data = response.json()
    results = data.get('results', [])
    print(results)
    all_people.extend(results)

[{'name': 'Luke Skywalker', 'height': '172', 'mass': '77', 'hair_color': 'blond', 'skin_color': 'fair', 'eye_color': 'blue', 'birth_year': '19BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/1/', 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/6/'], 'species': [], 'vehicles': ['https://swapi.dev/api/vehicles/14/', 'https://swapi.dev/api/vehicles/30/'], 'starships': ['https://swapi.dev/api/starships/12/', 'https://swapi.dev/api/starships/22/'], 'created': '2014-12-09T13:50:51.644000Z', 'edited': '2014-12-20T21:17:56.891000Z', 'url': 'https://swapi.dev/api/people/1/'}, {'name': 'C-3PO', 'height': '167', 'mass': '75', 'hair_color': 'n/a', 'skin_color': 'gold', 'eye_color': 'yellow', 'birth_year': '112BBY', 'gender': 'n/a', 'homeworld': 'https://swapi.dev/api/planets/1/', 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'], 'species': ['https://swapi.dev/api/species/2/'], 'vehicles': [], 'starships': [], 'created': '2014-12-10T15:10:51.357000Z', 'edited': '2014-12-20T21:17:50.309000Z', 'url': 'https://swapi.dev/api/people/2/'}, {'name': 'R2-D2', 'height': '96', 'mass': '32', 'hair_color': 'n/a', 'skin_color': 'white, blue', 'eye_color': 'red', 'birth_year': '33BBY', 'gender': 'n/a', 'homeworld': 'https://swapi.dev/api/planets/8/', 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'], 'species': ['https://swapi.dev/api/species/2/'], 'vehicles': [], 'starships': [], 'created': '2014-12-10T15:11:50.376000Z', 'edited': '2014-12-20T21:17:50.311000Z', 'url': 'https://swapi.dev/api/people/3/'}, {'name': 'Darth Vader', 'height': '202', 'mass': '136', 'hair_color': 'none', 'skin_color': 'white', 'eye_color': 'yellow', 'birth_year': '41.9BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/1/', 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/6/'], 'species': [], 'vehicles': [], 'starships': ['https://swapi.dev/api/starships/13/'], 'created': '2014-12-10T15:18:20.704000Z', 'edited': '2014-12-20T21:17:50.313000Z', 'url': 'https://swapi.dev/api/people/4/'}, {'name': 'Leia Organa', 'height': '150', 'mass': '49', 'hair_color': 'brown', 'skin_color': 'light', 'eye_color': 'brown', 'birth_year': '19BBY', 'gender': 'female', 'homeworld': 'https://swapi.dev/api/planets/2/', 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/6/'], 'species': [], 'vehicles': ['https://swapi.dev/api/vehicles/30/'], 'starships': [], 'created': '2014-12-10T15:20:09.791000Z', 'edited': '2014-12-20T21:17:50.315000Z', 'url': 'https://swapi.dev/api/people/5/'}, {'name': 'Owen Lars', 'height': '178', 'mass': '120', 'hair_color': 'brown, grey', 'skin_color': 'light', 'eye_color': 'blue', 'birth_year': '52BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/1/', 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'], 'species': [], 'vehicles': [], 'starships': [], 'created': '2014-12-10T15:52:14.024000Z', 'edited': '2014-12-20T21:17:50.317000Z', 'url': 'https://swapi.dev/api/people/6/'}, {'name': 'Beru Whitesun lars', 'height': '165', 'mass': '75', 'hair_color': 'brown', 'skin_color': 'light', 'eye_color': 'blue', 'birth_year': '47BBY', 'gender': 'female', 'homeworld': 'https://swapi.dev/api/planets/1/', 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'], 'species': [], 'vehicles': [], 'starships': [], 'created': '2014-12-10T15:53:41.121000Z', 'edited': '2014-12-20T21:17:50.319000Z', 'url': 'https://swapi.dev/api/people/7/'}, {'name': 'R5-D4', 'height': '97', 'mass': '32', 'hair_color': 'n/a', 'skin_color': 'white, red', 'eye_color': 'red', 'birth_year': 'unknown', 'gender': 'n/a', 'homeworld': 'https://swapi.dev/api/planets/1/', 'films': ['https://swapi.dev/api/films/1/'], 'species': ['https://swapi.dev/api/species/2/'], 'vehicles': [], 'starships': [], 'created': '2014-12-10T15:57:50.959000Z', 'edited': '2014-12-20T21:17:50.321000Z', 'url': 'https://swapi.dev/api/people/8/'}, {'name': 'Biggs Darklighter', 'height': '183', 'mass': '84', 'hair_color': 'black', 'skin_color': 'light', 'eye_color': 'brown', 'birth_year': '24BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/1/', 'films': ['https://swapi.dev/api/films/1/'], 'species': [], 'vehicles': [], 'starships': ['https://swapi.dev/api/starships/12/'], 'created': '2014-12-10T15:59:50.509000Z', 'edited': '2014-12-20T21:17:50.323000Z', 'url': 'https://swapi.dev/api/people/9/'}, {'name': 'Obi-Wan Kenobi', 'height': '182', 'mass': '77', 'hair_color': 'auburn, white', 'skin_color': 'fair', 'eye_color': 'blue-gray', 'birth_year': '57BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/20/', 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'], 'species': [], 'vehicles': ['https://swapi.dev/api/vehicles/38/'], 'starships': ['https://swapi.dev/api/starships/48/', 'https://swapi.dev/api/starships/59/', 'https://swapi.dev/api/starships/64/', 'https://swapi.dev/api/starships/65/', 'https://swapi.dev/api/starships/74/'], 'created': '2014-12-10T16:16:29.192000Z', 'edited': '2014-12-20T21:17:50.325000Z', 'url': 'https://swapi.dev/api/people/10/'}]
[{'name': 'Anakin Skywalker', 'height': '188', 'mass': '84', 'hair_color': 'blond', 'skin_color': 'fair', 'eye_color': 'blue', 'birth_year': '41.9BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/1/', 'films': ['https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'], 'species': [], 'vehicles': ['https://swapi.dev/api/vehicles/44/', 'https://swapi.dev/api/vehicles/46/'], 'starships': ['https://swapi.dev/api/starships/39/', 'https://swapi.dev/api/starships/59/', 'https://swapi.dev/api/starships/65/'], 'created': '2014-12-10T16:20:44.310000Z', 'edited': '2014-12-20T21:17:50.327000Z', 'url': 'https://swapi.dev/api/people/11/'}, {'name': 'Wilhuff Tarkin', 'height': '180', 'mass': 'unknown', 'hair_color': 'auburn, grey', 'skin_color': 'fair', 'eye_color': 'blue', 'birth_year': '64BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/21/', 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/6/'], 'species': [], 'vehicles': [], 'starships': [], 'created': '2014-12-10T16:26:56.138000Z', 'edited': '2014-12-20T21:17:50.330000Z', 'url': 'https://swapi.dev/api/people/12/'}, {'name': 'Chewbacca', 'height': '228', 'mass': '112', 'hair_color': 'brown', 'skin_color': 'unknown', 'eye_color': 'blue', 'birth_year': '200BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/14/', 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/6/'], 'species': ['https://swapi.dev/api/species/3/'], 'vehicles': ['https://swapi.dev/api/vehicles/19/'], 'starships': ['https://swapi.dev/api/starships/10/', 'https://swapi.dev/api/starships/22/'], 'created': '2014-12-10T16:42:45.066000Z', 'edited': '2014-12-20T21:17:50.332000Z', 'url': 'https://swapi.dev/api/people/13/'}, {'name': 'Han Solo', 'height': '180', 'mass': '80', 'hair_color': 'brown', 'skin_color': 'fair', 'eye_color': 'brown', 'birth_year': '29BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/22/', 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/'], 'species': [], 'vehicles': [], 'starships': ['https://swapi.dev/api/starships/10/', 'https://swapi.dev/api/starships/22/'], 'created': '2014-12-10T16:49:14.582000Z', 'edited': '2014-12-20T21:17:50.334000Z', 'url': 'https://swapi.dev/api/people/14/'}, {'name': 'Greedo', 'height': '173', 'mass': '74', 'hair_color': 'n/a', 'skin_color': 'green', 'eye_color': 'black', 'birth_year': '44BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/23/', 'films': ['https://swapi.dev/api/films/1/'], 'species': ['https://swapi.dev/api/species/4/'], 'vehicles': [], 'starships': [], 'created': '2014-12-10T17:03:30.334000Z', 'edited': '2014-12-20T21:17:50.336000Z', 'url': 'https://swapi.dev/api/people/15/'}, {'name': 'Jabba Desilijic Tiure', 'height': '175', 'mass': '1,358', 'hair_color': 'n/a', 'skin_color': 'green-tan, brown', 'eye_color': 'orange', 'birth_year': '600BBY', 'gender': 'hermaphrodite', 'homeworld': 'https://swapi.dev/api/planets/24/', 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/4/'], 'species': ['https://swapi.dev/api/species/5/'], 'vehicles': [], 'starships': [], 'created': '2014-12-10T17:11:31.638000Z', 'edited': '2014-12-20T21:17:50.338000Z', 'url': 'https://swapi.dev/api/people/16/'}, {'name': 'Wedge Antilles', 'height': '170', 'mass': '77', 'hair_color': 'brown', 'skin_color': 'fair', 'eye_color': 'hazel', 'birth_year': '21BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/22/', 'films': ['https://swapi.dev/api/films/1/', 'https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/'], 'species': [], 'vehicles': ['https://swapi.dev/api/vehicles/14/'], 'starships': ['https://swapi.dev/api/starships/12/'], 'created': '2014-12-12T11:08:06.469000Z', 'edited': '2014-12-20T21:17:50.341000Z', 'url': 'https://swapi.dev/api/people/18/'}, {'name': 'Jek Tono Porkins', 'height': '180', 'mass': '110', 'hair_color': 'brown', 'skin_color': 'fair', 'eye_color': 'blue', 'birth_year': 'unknown', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/26/', 'films': ['https://swapi.dev/api/films/1/'], 'species': [], 'vehicles': [], 'starships': ['https://swapi.dev/api/starships/12/'], 'created': '2014-12-12T11:16:56.569000Z', 'edited': '2014-12-20T21:17:50.343000Z', 'url': 'https://swapi.dev/api/people/19/'}, {'name': 'Yoda', 'height': '66', 'mass': '17', 'hair_color': 'white', 'skin_color': 'green', 'eye_color': 'brown', 'birth_year': '896BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/28/', 'films': ['https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'], 'species': ['https://swapi.dev/api/species/6/'], 'vehicles': [], 'starships': [], 'created': '2014-12-15T12:26:01.042000Z', 'edited': '2014-12-20T21:17:50.345000Z', 'url': 'https://swapi.dev/api/people/20/'}, {'name': 'Palpatine', 'height': '170', 'mass': '75', 'hair_color': 'grey', 'skin_color': 'pale', 'eye_color': 'yellow', 'birth_year': '82BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/8/', 'films': ['https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/4/', 'https://swapi.dev/api/films/5/', 'https://swapi.dev/api/films/6/'], 'species': [], 'vehicles': [], 'starships': [], 'created': '2014-12-15T12:48:05.971000Z', 'edited': '2014-12-20T21:17:50.347000Z', 'url': 'https://swapi.dev/api/people/21/'}]
[{'name': 'Boba Fett', 'height': '183', 'mass': '78.2', 'hair_color': 'black', 'skin_color': 'fair', 'eye_color': 'brown', 'birth_year': '31.5BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/10/', 'films': ['https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/', 'https://swapi.dev/api/films/5/'], 'species': [], 'vehicles': [], 'starships': ['https://swapi.dev/api/starships/21/'], 'created': '2014-12-15T12:49:32.457000Z', 'edited': '2014-12-20T21:17:50.349000Z', 'url': 'https://swapi.dev/api/people/22/'}, {'name': 'IG-88', 'height': '200', 'mass': '140', 'hair_color': 'none', 'skin_color': 'metal', 'eye_color': 'red', 'birth_year': '15BBY', 'gender': 'none', 'homeworld': 'https://swapi.dev/api/planets/28/', 'films': ['https://swapi.dev/api/films/2/'], 'species': ['https://swapi.dev/api/species/2/'], 'vehicles': [], 'starships': [], 'created': '2014-12-15T12:51:10.076000Z', 'edited': '2014-12-20T21:17:50.351000Z', 'url': 'https://swapi.dev/api/people/23/'}, {'name': 'Bossk', 'height': '190', 'mass': '113', 'hair_color': 'none', 'skin_color': 'green', 'eye_color': 'red', 'birth_year': '53BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/29/', 'films': ['https://swapi.dev/api/films/2/'], 'species': ['https://swapi.dev/api/species/7/'], 'vehicles': [], 'starships': [], 'created': '2014-12-15T12:53:49.297000Z', 'edited': '2014-12-20T21:17:50.355000Z', 'url': 'https://swapi.dev/api/people/24/'}, {'name': 'Lando Calrissian', 'height': '177', 'mass': '79', 'hair_color': 'black', 'skin_color': 'dark', 'eye_color': 'brown', 'birth_year': '31BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/30/', 'films': ['https://swapi.dev/api/films/2/', 'https://swapi.dev/api/films/3/'], 'species': [], 'vehicles': [], 'starships': ['https://swapi.dev/api/starships/10/'], 'created': '2014-12-15T12:56:32.683000Z', 'edited': '2014-12-20T21:17:50.357000Z', 'url': 'https://swapi.dev/api/people/25/'}, {'name': 'Lobot', 'height': '175', 'mass': '79', 'hair_color': 'none', 'skin_color': 'light', 'eye_color': 'blue', 'birth_year': '37BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/6/', 'films': ['https://swapi.dev/api/films/2/'], 'species': [], 'vehicles': [], 'starships': [], 'created': '2014-12-15T13:01:57.178000Z', 'edited': '2014-12-20T21:17:50.359000Z', 'url': 'https://swapi.dev/api/people/26/'}, {'name': 'Ackbar', 'height': '180', 'mass': '83', 'hair_color': 'none', 'skin_color': 'brown mottle', 'eye_color': 'orange', 'birth_year': '41BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/31/', 'films': ['https://swapi.dev/api/films/3/'], 'species': ['https://swapi.dev/api/species/8/'], 'vehicles': [], 'starships': [], 'created': '2014-12-18T11:07:50.584000Z', 'edited': '2014-12-20T21:17:50.362000Z', 'url': 'https://swapi.dev/api/people/27/'}, {'name': 'Mon Mothma', 'height': '150', 'mass': 'unknown', 'hair_color': 'auburn', 'skin_color': 'fair', 'eye_color': 'blue', 'birth_year': '48BBY', 'gender': 'female', 'homeworld': 'https://swapi.dev/api/planets/32/', 'films': ['https://swapi.dev/api/films/3/'], 'species': [], 'vehicles': [], 'starships': [], 'created': '2014-12-18T11:12:38.895000Z', 'edited': '2014-12-20T21:17:50.364000Z', 'url': 'https://swapi.dev/api/people/28/'}, {'name': 'Arvel Crynyd', 'height': 'unknown', 'mass': 'unknown', 'hair_color': 'brown', 'skin_color': 'fair', 'eye_color': 'brown', 'birth_year': 'unknown', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/28/', 'films': ['https://swapi.dev/api/films/3/'], 'species': [], 'vehicles': [], 'starships': ['https://swapi.dev/api/starships/28/'], 'created': '2014-12-18T11:16:33.020000Z', 'edited': '2014-12-20T21:17:50.367000Z', 'url': 'https://swapi.dev/api/people/29/'}, {'name': 'Wicket Systri Warrick', 'height': '88', 'mass': '20', 'hair_color': 'brown', 'skin_color': 'brown', 'eye_color': 'brown', 'birth_year': '8BBY', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/7/', 'films': ['https://swapi.dev/api/films/3/'], 'species': ['https://swapi.dev/api/species/9/'], 'vehicles': [], 'starships': [], 'created': '2014-12-18T11:21:58.954000Z', 'edited': '2014-12-20T21:17:50.369000Z', 'url': 'https://swapi.dev/api/people/30/'}, {'name': 'Nien Nunb', 'height': '160', 'mass': '68', 'hair_color': 'none', 'skin_color': 'grey', 'eye_color': 'black', 'birth_year': 'unknown', 'gender': 'male', 'homeworld': 'https://swapi.dev/api/planets/33/', 'films': ['https://swapi.dev/api/films/3/'], 'species': ['https://swapi.dev/api/species/10/'], 'vehicles': [], 'starships': ['https://swapi.dev/api/starships/10/'], 'created': '2014-12-18T11:26:18.541000Z', 'edited': '2014-12-20T21:17:50.371000Z', 'url': 'https://swapi.dev/api/people/31/'}]

In [3]:
# cleaning of people data
df_people = pd.DataFrame(all_people)
columns_to_drop = ['films','created','edited','created','vehicles','species',]  #
df_people.drop(columns_to_drop, axis=1, inplace=True)
df_people

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,starships,url
0,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,https://swapi.dev/api/planets/1/,"[https://swapi.dev/api/starships/12/, https://...",https://swapi.dev/api/people/1/
1,C-3PO,167,75,n/a,gold,yellow,112BBY,n/a,https://swapi.dev/api/planets/1/,[],https://swapi.dev/api/people/2/
2,R2-D2,96,32,n/a,"white, blue",red,33BBY,n/a,https://swapi.dev/api/planets/8/,[],https://swapi.dev/api/people/3/
3,Darth Vader,202,136,none,white,yellow,41.9BBY,male,https://swapi.dev/api/planets/1/,[https://swapi.dev/api/starships/13/],https://swapi.dev/api/people/4/
4,Leia Organa,150,49,brown,light,brown,19BBY,female,https://swapi.dev/api/planets/2/,[],https://swapi.dev/api/people/5/
...,...,...,...,...,...,...,...,...,...,...,...
77,Grievous,216,159,none,"brown, white","green, yellow",unknown,male,https://swapi.dev/api/planets/59/,[https://swapi.dev/api/starships/74/],https://swapi.dev/api/people/79/
78,Tarfful,234,136,brown,brown,blue,unknown,male,https://swapi.dev/api/planets/14/,[],https://swapi.dev/api/people/80/
79,Raymus Antilles,188,79,brown,light,brown,unknown,male,https://swapi.dev/api/planets/2/,[],https://swapi.dev/api/people/81/
80,Sly Moore,178,48,none,pale,white,unknown,female,https://swapi.dev/api/planets/60/,[],https://swapi.dev/api/people/82/
81,Tion Medon,206,80,none,grey,black,unknown,male,https://swapi.dev/api/planets/12/,[],https://swapi.dev/api/people/83/

In [22]:
#some more cleaning
def extract_id(url):
    if pd.isnull(url) or not isinstance(url, str):
        return url
    return int(url.strip('/').split('/')[-1])

df_people['planet_id'] = df_people['url'].apply(extract_id)

if 'homeworld' in df_people.columns:
    df_people['homeworld'] = df_people['homeworld'].apply(extract_id)

df_people

,name,height,mass,hair_color,skin_color,eye_color,birth_year,gender,homeworld,starships,url,unique_id,planet_id
0,Luke Skywalker,172,77,blond,fair,blue,19BBY,male,1,"['https://swapi.dev/api/starships/12/', 'https...",https://swapi.dev/api/people/1/,1,1
1,C-3PO,167,75,n/a,gold,yellow,112BBY,n/a,1,[],https://swapi.dev/api/people/2/,2,2
2,R2-D2,96,32,n/a,"white, blue",red,33BBY,n/a,8,[],https://swapi.dev/api/people/3/,3,3
3,Darth Vader,202,136,none,white,yellow,41.9BBY,male,1,['https://swapi.dev/api/starships/13/'],https://swapi.dev/api/people/4/,4,4
4,Leia Organa,150,49,brown,light,brown,19BBY,female,2,[],https://swapi.dev/api/people/5/,5,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...
77,Grievous,216,159,none,"brown, white","green, yellow",unknown,male,59,['https://swapi.dev/api/starships/74/'],https://swapi.dev/api/people/79/,79,79
78,Tarfful,234,136,brown,brown,blue,unknown,male,14,[],https://swapi.dev/api/people/80/,80,80
79,Raymus Antilles,188,79,brown,light,brown,unknown,male,2,[],https://swapi.dev/api/people/81/,81,81
80,Sly Moore,178,48,none,pale,white,unknown,female,60,[],https://swapi.dev/api/people/82/,82,82
81,Tion Medon,206,80,none,grey,black,unknown,male,12,[],https://swapi.dev/api/people/83/,83,83

In [5]:
#checking the data types of people data
df_people.dtypes

name          object
height        object
mass          object
hair_color    object
skin_color    object
eye_color     object
birth_year    object
gender        object
homeworld      int64
starships     object
url           object
unique_id      int64
dtype: object

In [20]:
#converting dtypes to strings
for column in df_people:
    if df_people[column].dtype == 'object':
        df_people[column] = df_people[column].astype(str)

In [23]:
#loading into sql table
cursor.execute(f"CREATE TABLE IF NOT EXISTS people ({', '.join(df_people.columns)})")
conn.commit()
df_people.to_sql('people', conn, if_exists='replace', index=False)

82

In [14]:
#same procedure for planets
url = 'https://swapi.dev/api/planets/'
all_planets = []

while url:
    response = requests.get(url)
    data = response.json()
    results = data.get('results', [])
    #print(results)
    all_planets.extend(results)
    url = data.get('next')

In [15]:
df_planets= pd.DataFrame(all_planets)
df_planets.head()

,name,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population,residents,films,created,edited,url
0,Tatooine,23,304,10465,arid,1 standard,desert,1,200000,"[https://swapi.dev/api/people/1/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-09T13:50:49.641000Z,2014-12-20T20:58:18.411000Z,https://swapi.dev/api/planets/1/
1,Alderaan,24,364,12500,temperate,1 standard,"grasslands, mountains",40,2000000000,"[https://swapi.dev/api/people/5/, https://swap...","[https://swapi.dev/api/films/1/, https://swapi...",2014-12-10T11:35:48.479000Z,2014-12-20T20:58:18.420000Z,https://swapi.dev/api/planets/2/
2,Yavin IV,24,4818,10200,"temperate, tropical",1 standard,"jungle, rainforests",8,1000,[],[https://swapi.dev/api/films/1/],2014-12-10T11:37:19.144000Z,2014-12-20T20:58:18.421000Z,https://swapi.dev/api/planets/3/
3,Hoth,23,549,7200,frozen,1.1 standard,"tundra, ice caves, mountain ranges",100,unknown,[],[https://swapi.dev/api/films/2/],2014-12-10T11:39:13.934000Z,2014-12-20T20:58:18.423000Z,https://swapi.dev/api/planets/4/
4,Dagobah,23,341,8900,murky,N/A,"swamp, jungles",8,unknown,[],"[https://swapi.dev/api/films/2/, https://swapi...",2014-12-10T11:42:22.590000Z,2014-12-20T20:58:18.425000Z,https://swapi.dev/api/planets/5/

In [60]:
df_planets = pd.DataFrame(all_planets)
columns_to_drop = ['films','created','edited']  #
df_planets.drop(columns_to_drop, axis=1, inplace=True)
df_planets.rename(columns={'name': 'planet_name'}, inplace = True)

def extract_id(url):
    if pd.isnull(url) or not isinstance(url, str):
        return url
    return int(url.strip('/').split('/')[-1])

df_planets['unique_planet_id'] = df_planets['url'].apply(extract_id)

df_planets.head()

,planet_name,rotation_period,orbital_period,diameter,climate,gravity,terrain,surface_water,population,residents,url,unique_planet_id
0,Tatooine,23,304,10465,arid,1 standard,desert,1,200000,"[https://swapi.dev/api/people/1/, https://swap...",https://swapi.dev/api/planets/1/,1
1,Alderaan,24,364,12500,temperate,1 standard,"grasslands, mountains",40,2000000000,"[https://swapi.dev/api/people/5/, https://swap...",https://swapi.dev/api/planets/2/,2
2,Yavin IV,24,4818,10200,"temperate, tropical",1 standard,"jungle, rainforests",8,1000,[],https://swapi.dev/api/planets/3/,3
3,Hoth,23,549,7200,frozen,1.1 standard,"tundra, ice caves, mountain ranges",100,unknown,[],https://swapi.dev/api/planets/4/,4
4,Dagobah,23,341,8900,murky,N/A,"swamp, jungles",8,unknown,[],https://swapi.dev/api/planets/5/,5

In [61]:
#cursor.execute('DROP TABLE IF EXISTS people')
for column in df_planets:
    if df_planets[column].dtype == 'object':
        df_planets[column] = df_planets[column].astype(str)

In [62]:
# Step 4: SQLite Database Creation
with sqlite3.connect('star_wars.db') as conn:
    cursor = conn.cursor()

In [63]:
cursor.execute(f"CREATE TABLE IF NOT EXISTS planets ({', '.join(df_planets.columns)})")
conn.commit()
df_planets.to_sql('planets', conn, if_exists='replace', index=False)

60

In [64]:
#SQL SELECT
pd.read_sql(
    '''
        SELECT 
            people.name
        FROM 
            people
    
    ''', 
    conn
)

               name
0    Luke Skywalker
1             C-3PO
2             R2-D2
3       Darth Vader
4       Leia Organa
..              ...
77         Grievous
78          Tarfful
79  Raymus Antilles
80        Sly Moore
81       Tion Medon

[82 rows x 1 columns]

In [65]:
#inner join to find out which person is from which planet
pd.read_sql(
    '''
        SELECT 
            people.name,
            planets.planet_name
        FROM 
            people
        INNER JOIN 
            planets ON people.planet_id = planets.unique_planet_id
        
    ''', 
    conn
)

                     name     planet_name
0          Luke Skywalker        Tatooine
1                   C-3PO        Alderaan
2                   R2-D2        Yavin IV
3             Darth Vader            Hoth
4             Leia Organa         Dagobah
5               Owen Lars          Bespin
6      Beru Whitesun lars           Endor
7                   R5-D4           Naboo
8       Biggs Darklighter       Coruscant
9          Obi-Wan Kenobi          Kamino
10       Anakin Skywalker        Geonosis
11         Wilhuff Tarkin          Utapau
12              Chewbacca        Mustafar
13               Han Solo        Kashyyyk
14                 Greedo     Polis Massa
15  Jabba Desilijic Tiure         Mygeeto
16         Wedge Antilles  Cato Neimoidia
17       Jek Tono Porkins       Saleucami
18                   Yoda         Stewjon
19              Palpatine          Eriadu
20              Boba Fett        Corellia
21                  IG-88           Rodia
22                  Bossk       Nal Hutta
23       Lando Calrissian       Dantooine
24                  Lobot      Bestine IV
25                 Ackbar     Ord Mantell
26             Mon Mothma         unknown
27           Arvel Crynyd       Trandosha
28  Wicket Systri Warrick         Socorro
29              Nien Nunb        Mon Cala
30           Qui-Gon Jinn       Chandrila
31            Nute Gunray         Sullust
32          Finis Valorum        Toydaria
33          Padmé Amidala       Malastare
34          Jar Jar Binks        Dathomir
35           Roos Tarpals          Ryloth
36             Rugor Nass     Aleen Minor
37               Ric Olié         Vulpter
38                  Watto         Troiken
39                Sebulba            Tund
40          Quarsh Panaka      Haruun Kal
41         Shmi Skywalker           Cerea
42             Darth Maul     Glee Anselm
43            Bib Fortuna        Iridonia
44            Ayla Secura         Tholoth
45           Ratts Tyerel         Iktotch
46               Dud Bolt         Quermia
47                Gasgano           Dorin
48         Ben Quadinaros        Champala
49             Mace Windu          Mirial
50           Ki-Adi-Mundi         Serenno
51              Kit Fisto    Concord Dawn
52              Eeth Koth           Zolan
53             Adi Gallia            Ojom
54            Saesee Tiin           Skako
55            Yarael Poof      Muunilinst
56               Plo Koon           Shili
57             Mas Amedda           Kalee
58           Gregar Typho          Umbara

In [66]:
#left join to find the eye_color and planet_name :D
pd.read_sql(
    '''
        SELECT 
            people.name,
            people.eye_color,
            planets.planet_name
        FROM 
            people
        LEFT JOIN 
            planets ON people.planet_id = planets.unique_planet_id
        
    ''', 
    conn
)

               name      eye_color planet_name
0    Luke Skywalker           blue    Tatooine
1             C-3PO         yellow    Alderaan
2             R2-D2            red    Yavin IV
3       Darth Vader         yellow        Hoth
4       Leia Organa          brown     Dagobah
..              ...            ...         ...
77         Grievous  green, yellow        None
78          Tarfful           blue        None
79  Raymus Antilles          brown        None
80        Sly Moore          white        None
81       Tion Medon          black        None

[82 rows x 3 columns]

In [67]:
#Group by to find out the eyecolor frequency of people from different planets
pd.read_sql(
    '''
        SELECT 
            people.eye_color,
            COUNT (people.eye_color) as nb_eye_color,
            planets.planet_name
        FROM 
            people
        LEFT JOIN 
            planets ON people.planet_id = planets.unique_planet_id
        GROUP BY
        people.eye_color
        
    ''', 
    conn
)

        eye_color  nb_eye_color     planet_name
0           black             9     Polis Massa
1            blue            19        Tatooine
2       blue-gray             1          Kamino
3           brown            20         Dagobah
4            gold             1            None
5   green, yellow             1            None
6           hazel             2  Cato Neimoidia
7          orange             8         Mygeeto
8            pink             1        Iridonia
9             red             5        Yavin IV
10      red, blue             1            None
11        unknown             2         Iktotch
12          white             1            None
13         yellow            11        Alderaan

In [69]:
# having to find out the relation between skin_color and planet climate
pd.read_sql(
    '''
        SELECT 
            planet_name,
            people.skin_color,
            COUNT (people.skin_color) as nb_skin_color,
            planets.climate
        FROM 
            people
        LEFT JOIN 
            planets ON people.planet_id = planets.unique_planet_id
        GROUP BY
        people.skin_color
        HAVING
        nb_skin_color > 3
        
    ''', 
    conn
)

   planet_name skin_color  nb_skin_color                climate
0      Socorro      brown              4                   arid
1    Dantooine       dark              5              temperate
2     Tatooine       fair             17                   arid
3  Polis Massa      green              6  artificial temperate
4     Mon Cala       grey              6              temperate
5      Dagobah      light              9                  murky
6       Eriadu       pale              5               polluted

In [78]:
#CTE
pd.read_sql(
    '''WITH skin_climate as (
        SELECT 
            planet_name,
            people.skin_color,
            COUNT (people.skin_color) as nb_skin_color,
            planets.climate
        FROM 
            people
        LEFT JOIN 
            planets ON people.planet_id = planets.unique_planet_id
        GROUP BY
        people.skin_color
        HAVING
        nb_skin_color > 3
    )

    SELECT 
    planet_name,
    skin_color
    FROM
    skin_climate
    WHERE
    climate = "arid"
    ''', 
    conn
)

  planet_name skin_color
0     Socorro      brown
1    Tatooine       fair

In [79]:

conn.commit()
conn.close()